spring:
  # db
  datasource:
    url: "jdbc:h2:file:./db/myblog;AUTO_SERVER=TRUE"
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  # schema
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
  # multipart
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# logs
logging:
  level:
    ru.yandex.practicum: debug
    org.springframework.web.servlet.DispatcherServlet: debug
# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"